language: python
# ===== Linux ======
os: linux
dist: xenial
python:
  - 3.6
  - 3.7
  - 3.8
  - "3.9-dev"
before_install:
  - python --version
  - python3 -m pip install --upgrade pip
install:
  - echo $TRAVIS_OS_NAME
  - pip install ".[test]"
script: pytest
after_success:
  - codecov  # submit coverage to codecov.io
